# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Tue Jul  4 14:42:29 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1135, 811)
        MainWindow.setWindowTitle("")
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Toolbar = QtGui.QWidget(self.centralwidget)
        self.Toolbar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Toolbar.setObjectName("Toolbar")
        self.horizontalLayout = QtGui.QHBoxLayout(self.Toolbar)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Lsdrdvc = QtGui.QLabel(self.Toolbar)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Lsdrdvc.sizePolicy().hasHeightForWidth())
        self.Lsdrdvc.setSizePolicy(sizePolicy)
        self.Lsdrdvc.setMinimumSize(QtCore.QSize(86, 0))
        self.Lsdrdvc.setMaximumSize(QtCore.QSize(86, 16777215))
        self.Lsdrdvc.setObjectName("Lsdrdvc")
        self.horizontalLayout.addWidget(self.Lsdrdvc)
        self.CBsdr = QtGui.QComboBox(self.Toolbar)
        self.CBsdr.setMinimumSize(QtCore.QSize(85, 0))
        self.CBsdr.setMaximumSize(QtCore.QSize(125, 16777215))
        self.CBsdr.setObjectName("CBsdr")
        self.horizontalLayout.addWidget(self.CBsdr)
        self.Lsdrrate = QtGui.QLabel(self.Toolbar)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Lsdrrate.sizePolicy().hasHeightForWidth())
        self.Lsdrrate.setSizePolicy(sizePolicy)
        self.Lsdrrate.setMinimumSize(QtCore.QSize(86, 0))
        self.Lsdrrate.setMaximumSize(QtCore.QSize(86, 16777215))
        self.Lsdrrate.setObjectName("Lsdrrate")
        self.horizontalLayout.addWidget(self.Lsdrrate)
        self.CBsdrrate = QtGui.QComboBox(self.Toolbar)
        self.CBsdrrate.setMinimumSize(QtCore.QSize(75, 0))
        self.CBsdrrate.setMaximumSize(QtCore.QSize(90, 16777215))
        self.CBsdrrate.setObjectName("CBsdrrate")
        self.horizontalLayout.addWidget(self.CBsdrrate)
        self.TBstartsdr = QtGui.QToolButton(self.Toolbar)
        self.TBstartsdr.setIconSize(QtCore.QSize(32, 32))
        self.TBstartsdr.setObjectName("TBstartsdr")
        self.horizontalLayout.addWidget(self.TBstartsdr)
        self.space1 = QtGui.QLabel(self.Toolbar)
        self.space1.setMaximumSize(QtCore.QSize(120, 16777215))
        self.space1.setText("")
        self.space1.setObjectName("space1")
        self.horizontalLayout.addWidget(self.space1)
        self.TBping = QtGui.QToolButton(self.Toolbar)
        self.TBping.setIconSize(QtCore.QSize(32, 32))
        self.TBping.setObjectName("TBping")
        self.horizontalLayout.addWidget(self.TBping)
        self.TBsend = QtGui.QToolButton(self.Toolbar)
        self.TBsend.setIconSize(QtCore.QSize(32, 32))
        self.TBsend.setCheckable(False)
        self.TBsend.setObjectName("TBsend")
        self.horizontalLayout.addWidget(self.TBsend)
        self.space2 = QtGui.QLabel(self.Toolbar)
        self.space2.setText("")
        self.space2.setObjectName("space2")
        self.horizontalLayout.addWidget(self.space2)
        self.verticalLayout.addWidget(self.Toolbar)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tabFlight = QtGui.QWidget()
        self.tabFlight.setObjectName("tabFlight")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tabFlight)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Lworldmap = QtGui.QLabel(self.tabFlight)
        self.Lworldmap.setMinimumSize(QtCore.QSize(640, 360))
        self.Lworldmap.setText("")
        self.Lworldmap.setScaledContents(True)
        self.Lworldmap.setObjectName("Lworldmap")
        self.verticalLayout_3.addWidget(self.Lworldmap)
        self.line = QtGui.QFrame(self.tabFlight)
        self.line.setWindowModality(QtCore.Qt.WindowModal)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.widget = QtGui.QWidget(self.tabFlight)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 250))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Lradar = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Lradar.sizePolicy().hasHeightForWidth())
        self.Lradar.setSizePolicy(sizePolicy)
        self.Lradar.setMinimumSize(QtCore.QSize(200, 200))
        self.Lradar.setMaximumSize(QtCore.QSize(400, 400))
        self.Lradar.setText("")
        self.Lradar.setObjectName("Lradar")
        self.horizontalLayout_2.addWidget(self.Lradar)
        self.VLsatinfo = QtGui.QVBoxLayout()
        self.VLsatinfo.setSpacing(1)
        self.VLsatinfo.setObjectName("VLsatinfo")
        self.Lsalelliteinfo = QtGui.QLabel(self.widget)
        self.Lsalelliteinfo.setObjectName("Lsalelliteinfo")
        self.VLsatinfo.addWidget(self.Lsalelliteinfo)
        self.LEsatelliteinfo = QtGui.QTextEdit(self.widget)
        self.LEsatelliteinfo.setMaximumSize(QtCore.QSize(10000000, 300))
        self.LEsatelliteinfo.setReadOnly(True)
        self.LEsatelliteinfo.setObjectName("LEsatelliteinfo")
        self.VLsatinfo.addWidget(self.LEsatelliteinfo)
        self.horizontalLayout_2.addLayout(self.VLsatinfo)
        self.verticalLayout_3.addWidget(self.widget)
        self.tabWidget.addTab(self.tabFlight, "")
        self.tabRequest = QtGui.QWidget()
        self.tabRequest.setObjectName("tabRequest")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabRequest)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_2 = QtGui.QWidget(self.tabRequest)
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 27))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Lcfgfile = QtGui.QLabel(self.widget_2)
        self.Lcfgfile.setMaximumSize(QtCore.QSize(80, 16777215))
        self.Lcfgfile.setObjectName("Lcfgfile")
        self.horizontalLayout_4.addWidget(self.Lcfgfile)
        self.LEcfgfile = QtGui.QLineEdit(self.widget_2)
        self.LEcfgfile.setMaximumSize(QtCore.QSize(300, 16777215))
        self.LEcfgfile.setObjectName("LEcfgfile")
        self.horizontalLayout_4.addWidget(self.LEcfgfile)
        self.Bcfgload = QtGui.QPushButton(self.widget_2)
        self.Bcfgload.setMaximumSize(QtCore.QSize(80, 16777215))
        self.Bcfgload.setObjectName("Bcfgload")
        self.horizontalLayout_4.addWidget(self.Bcfgload)
        self.Bcfgsaveas = QtGui.QPushButton(self.widget_2)
        self.Bcfgsaveas.setMaximumSize(QtCore.QSize(80, 16777215))
        self.Bcfgsaveas.setObjectName("Bcfgsaveas")
        self.horizontalLayout_4.addWidget(self.Bcfgsaveas)
        self.space3 = QtGui.QLabel(self.widget_2)
        self.space3.setText("")
        self.space3.setObjectName("space3")
        self.horizontalLayout_4.addWidget(self.space3)
        self.Buncheckall = QtGui.QPushButton(self.widget_2)
        self.Buncheckall.setMaximumSize(QtCore.QSize(90, 16777215))
        self.Buncheckall.setObjectName("Buncheckall")
        self.horizontalLayout_4.addWidget(self.Buncheckall)
        self.Bcheckall = QtGui.QPushButton(self.widget_2)
        self.Bcheckall.setMaximumSize(QtCore.QSize(80, 16777215))
        self.Bcheckall.setObjectName("Bcheckall")
        self.horizontalLayout_4.addWidget(self.Bcheckall)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.widget_3 = QtGui.QWidget(self.tabRequest)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.GBobdh = QtGui.QGroupBox(self.widget_3)
        self.GBobdh.setAutoFillBackground(False)
        self.GBobdh.setAlignment(QtCore.Qt.AlignCenter)
        self.GBobdh.setFlat(False)
        self.GBobdh.setCheckable(False)
        self.GBobdh.setChecked(False)
        self.GBobdh.setObjectName("GBobdh")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.GBobdh)
        self.verticalLayout_4.setSpacing(3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3.addWidget(self.GBobdh)
        self.VL1 = QtGui.QFrame(self.widget_3)
        self.VL1.setFrameShape(QtGui.QFrame.VLine)
        self.VL1.setFrameShadow(QtGui.QFrame.Sunken)
        self.VL1.setObjectName("VL1")
        self.horizontalLayout_3.addWidget(self.VL1)
        self.GBeps = QtGui.QGroupBox(self.widget_3)
        self.GBeps.setObjectName("GBeps")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.GBeps)
        self.verticalLayout_5.setSpacing(3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_3.addWidget(self.GBeps)
        self.VL2 = QtGui.QFrame(self.widget_3)
        self.VL2.setFrameShape(QtGui.QFrame.VLine)
        self.VL2.setFrameShadow(QtGui.QFrame.Sunken)
        self.VL2.setObjectName("VL2")
        self.horizontalLayout_3.addWidget(self.VL2)
        self.GBttc = QtGui.QGroupBox(self.widget_3)
        self.GBttc.setObjectName("GBttc")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.GBttc)
        self.verticalLayout_6.setSpacing(3)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_3.addWidget(self.GBttc)
        self.VL3 = QtGui.QFrame(self.widget_3)
        self.VL3.setFrameShape(QtGui.QFrame.VLine)
        self.VL3.setFrameShadow(QtGui.QFrame.Sunken)
        self.VL3.setObjectName("VL3")
        self.horizontalLayout_3.addWidget(self.VL3)
        self.GBpayloads = QtGui.QGroupBox(self.widget_3)
        self.GBpayloads.setBaseSize(QtCore.QSize(0, 0))
        self.GBpayloads.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.GBpayloads.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.GBpayloads.setObjectName("GBpayloads")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.GBpayloads)
        self.verticalLayout_7.setSpacing(3)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_3.addWidget(self.GBpayloads)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.tabWidget.addTab(self.tabRequest, "")
        self.tabSatellite = QtGui.QWidget()
        self.tabSatellite.setObjectName("tabSatellite")
        self.tabWidget.addTab(self.tabSatellite, "")
        self.tabSignal = QtGui.QWidget()
        self.tabSignal.setObjectName("tabSignal")
        self.tabWidget.addTab(self.tabSignal, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.LEeventlog = QtGui.QTextEdit(self.centralwidget)
        self.LEeventlog.setMinimumSize(QtCore.QSize(0, 80))
        self.LEeventlog.setMaximumSize(QtCore.QSize(16777215, 80))
        self.LEeventlog.setReadOnly(True)
        self.LEeventlog.setObjectName("LEeventlog")
        self.verticalLayout.addWidget(self.LEeventlog)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1135, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOptions = QtGui.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuEvent_log = QtGui.QMenu(self.menuView)
        self.menuEvent_log.setObjectName("menuEvent_log")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionToolbar = QtGui.QAction(MainWindow)
        self.actionToolbar.setObjectName("actionToolbar")
        self.actionSettings = QtGui.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionLower_side = QtGui.QAction(MainWindow)
        self.actionLower_side.setObjectName("actionLower_side")
        self.actionRight_side = QtGui.QAction(MainWindow)
        self.actionRight_side.setObjectName("actionRight_side")
        self.actionLeft_side = QtGui.QAction(MainWindow)
        self.actionLeft_side.setObjectName("actionLeft_side")
        self.actionUnshow = QtGui.QAction(MainWindow)
        self.actionUnshow.setObjectName("actionUnshow")
        self.menuFile.addAction(self.actionExit)
        self.menuOptions.addAction(self.actionSettings)
        self.menuHelp.addAction(self.actionAbout)
        self.menuEvent_log.addAction(self.actionLower_side)
        self.menuEvent_log.addAction(self.actionRight_side)
        self.menuEvent_log.addAction(self.actionLeft_side)
        self.menuEvent_log.addAction(self.actionUnshow)
        self.menuView.addAction(self.actionToolbar)
        self.menuView.addAction(self.menuEvent_log.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        self.Lsdrdvc.setText(QtGui.QApplication.translate("MainWindow", "SDR Device:", None, QtGui.QApplication.UnicodeUTF8))
        self.Lsdrrate.setText(QtGui.QApplication.translate("MainWindow", "Sample rate:", None, QtGui.QApplication.UnicodeUTF8))
        self.TBstartsdr.setText(QtGui.QApplication.translate("MainWindow", "Start SDR", None, QtGui.QApplication.UnicodeUTF8))
        self.TBping.setText(QtGui.QApplication.translate("MainWindow", "Ping", None, QtGui.QApplication.UnicodeUTF8))
        self.TBsend.setText(QtGui.QApplication.translate("MainWindow", "Send request", None, QtGui.QApplication.UnicodeUTF8))
        self.Lsalelliteinfo.setText(QtGui.QApplication.translate("MainWindow", "Satellite flight info", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFlight), QtGui.QApplication.translate("MainWindow", "Flight Data", None, QtGui.QApplication.UnicodeUTF8))
        self.Lcfgfile.setText(QtGui.QApplication.translate("MainWindow", "Config. file:", None, QtGui.QApplication.UnicodeUTF8))
        self.Bcfgload.setText(QtGui.QApplication.translate("MainWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.Bcfgsaveas.setText(QtGui.QApplication.translate("MainWindow", "Save As", None, QtGui.QApplication.UnicodeUTF8))
        self.Buncheckall.setText(QtGui.QApplication.translate("MainWindow", "Uncheck All", None, QtGui.QApplication.UnicodeUTF8))
        self.Bcheckall.setText(QtGui.QApplication.translate("MainWindow", "Check All", None, QtGui.QApplication.UnicodeUTF8))
        self.GBobdh.setTitle(QtGui.QApplication.translate("MainWindow", "OBDH", None, QtGui.QApplication.UnicodeUTF8))
        self.GBeps.setTitle(QtGui.QApplication.translate("MainWindow", "EPS", None, QtGui.QApplication.UnicodeUTF8))
        self.GBttc.setTitle(QtGui.QApplication.translate("MainWindow", "TTC", None, QtGui.QApplication.UnicodeUTF8))
        self.GBpayloads.setTitle(QtGui.QApplication.translate("MainWindow", "Payloads", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRequest), QtGui.QApplication.translate("MainWindow", "Request Data", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSatellite), QtGui.QApplication.translate("MainWindow", "Satellite Data", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSignal), QtGui.QApplication.translate("MainWindow", "Signal Data", None, QtGui.QApplication.UnicodeUTF8))
        self.LEeventlog.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuOptions.setTitle(QtGui.QApplication.translate("MainWindow", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("MainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEvent_log.setTitle(QtGui.QApplication.translate("MainWindow", "Event log", None, QtGui.QApplication.UnicodeUTF8))
        self.actionToolbar.setText(QtGui.QApplication.translate("MainWindow", "Toolbar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSettings.setText(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLower_side.setText(QtGui.QApplication.translate("MainWindow", "Lower side", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRight_side.setText(QtGui.QApplication.translate("MainWindow", "Right side", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLeft_side.setText(QtGui.QApplication.translate("MainWindow", "Left side", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUnshow.setText(QtGui.QApplication.translate("MainWindow", "Unshow", None, QtGui.QApplication.UnicodeUTF8))

